// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	entity "github.com/supressionstop/xenking_test_1/internal/usecase/entity"
)

// CalculateDiffer is an autogenerated mock type for the CalculateDiffer type
type CalculateDiffer struct {
	mock.Mock
}

type CalculateDiffer_Expecter struct {
	mock *mock.Mock
}

func (_m *CalculateDiffer) EXPECT() *CalculateDiffer_Expecter {
	return &CalculateDiffer_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: prev, curr
func (_m *CalculateDiffer) Execute(prev entity.LineMap, curr entity.LineMap) (entity.LinesDiff, error) {
	ret := _m.Called(prev, curr)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 entity.LinesDiff
	var r1 error
	if rf, ok := ret.Get(0).(func(entity.LineMap, entity.LineMap) (entity.LinesDiff, error)); ok {
		return rf(prev, curr)
	}
	if rf, ok := ret.Get(0).(func(entity.LineMap, entity.LineMap) entity.LinesDiff); ok {
		r0 = rf(prev, curr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entity.LinesDiff)
		}
	}

	if rf, ok := ret.Get(1).(func(entity.LineMap, entity.LineMap) error); ok {
		r1 = rf(prev, curr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CalculateDiffer_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type CalculateDiffer_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - prev entity.LineMap
//   - curr entity.LineMap
func (_e *CalculateDiffer_Expecter) Execute(prev interface{}, curr interface{}) *CalculateDiffer_Execute_Call {
	return &CalculateDiffer_Execute_Call{Call: _e.mock.On("Execute", prev, curr)}
}

func (_c *CalculateDiffer_Execute_Call) Run(run func(prev entity.LineMap, curr entity.LineMap)) *CalculateDiffer_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(entity.LineMap), args[1].(entity.LineMap))
	})
	return _c
}

func (_c *CalculateDiffer_Execute_Call) Return(_a0 entity.LinesDiff, _a1 error) *CalculateDiffer_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CalculateDiffer_Execute_Call) RunAndReturn(run func(entity.LineMap, entity.LineMap) (entity.LinesDiff, error)) *CalculateDiffer_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewCalculateDiffer creates a new instance of CalculateDiffer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCalculateDiffer(t interface {
	mock.TestingT
	Cleanup(func())
}) *CalculateDiffer {
	mock := &CalculateDiffer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
