// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/supressionstop/xenking_test_1/internal/usecase/entity"
)

// LineRepository is an autogenerated mock type for the LineRepository type
type LineRepository struct {
	mock.Mock
}

type LineRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *LineRepository) EXPECT() *LineRepository_Expecter {
	return &LineRepository_Expecter{mock: &_m.Mock}
}

// GetRecentLines provides a mock function with given fields: ctx, sports
func (_m *LineRepository) GetRecentLines(ctx context.Context, sports []string) ([]entity.Line, error) {
	ret := _m.Called(ctx, sports)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentLines")
	}

	var r0 []entity.Line
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]entity.Line, error)); ok {
		return rf(ctx, sports)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []entity.Line); ok {
		r0 = rf(ctx, sports)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Line)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, sports)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LineRepository_GetRecentLines_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecentLines'
type LineRepository_GetRecentLines_Call struct {
	*mock.Call
}

// GetRecentLines is a helper method to define mock.On call
//   - ctx context.Context
//   - sports []string
func (_e *LineRepository_Expecter) GetRecentLines(ctx interface{}, sports interface{}) *LineRepository_GetRecentLines_Call {
	return &LineRepository_GetRecentLines_Call{Call: _e.mock.On("GetRecentLines", ctx, sports)}
}

func (_c *LineRepository_GetRecentLines_Call) Run(run func(ctx context.Context, sports []string)) *LineRepository_GetRecentLines_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *LineRepository_GetRecentLines_Call) Return(_a0 []entity.Line, _a1 error) *LineRepository_GetRecentLines_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LineRepository_GetRecentLines_Call) RunAndReturn(run func(context.Context, []string) ([]entity.Line, error)) *LineRepository_GetRecentLines_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, line
func (_m *LineRepository) Save(ctx context.Context, line entity.Line) (entity.Line, error) {
	ret := _m.Called(ctx, line)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 entity.Line
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Line) (entity.Line, error)); ok {
		return rf(ctx, line)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Line) entity.Line); ok {
		r0 = rf(ctx, line)
	} else {
		r0 = ret.Get(0).(entity.Line)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Line) error); ok {
		r1 = rf(ctx, line)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LineRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type LineRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - line entity.Line
func (_e *LineRepository_Expecter) Save(ctx interface{}, line interface{}) *LineRepository_Save_Call {
	return &LineRepository_Save_Call{Call: _e.mock.On("Save", ctx, line)}
}

func (_c *LineRepository_Save_Call) Run(run func(ctx context.Context, line entity.Line)) *LineRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Line))
	})
	return _c
}

func (_c *LineRepository_Save_Call) Return(_a0 entity.Line, _a1 error) *LineRepository_Save_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LineRepository_Save_Call) RunAndReturn(run func(context.Context, entity.Line) (entity.Line, error)) *LineRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewLineRepository creates a new instance of LineRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLineRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LineRepository {
	mock := &LineRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
