// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/supressionstop/xenking_test_1/internal/usecase/entity"
)

// RecentLinesGetter is an autogenerated mock type for the RecentLinesGetter type
type RecentLinesGetter struct {
	mock.Mock
}

type RecentLinesGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *RecentLinesGetter) EXPECT() *RecentLinesGetter_Expecter {
	return &RecentLinesGetter_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, sports
func (_m *RecentLinesGetter) Execute(ctx context.Context, sports []string) (entity.LineMap, error) {
	ret := _m.Called(ctx, sports)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 entity.LineMap
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (entity.LineMap, error)); ok {
		return rf(ctx, sports)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) entity.LineMap); ok {
		r0 = rf(ctx, sports)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entity.LineMap)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, sports)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RecentLinesGetter_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type RecentLinesGetter_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - sports []string
func (_e *RecentLinesGetter_Expecter) Execute(ctx interface{}, sports interface{}) *RecentLinesGetter_Execute_Call {
	return &RecentLinesGetter_Execute_Call{Call: _e.mock.On("Execute", ctx, sports)}
}

func (_c *RecentLinesGetter_Execute_Call) Run(run func(ctx context.Context, sports []string)) *RecentLinesGetter_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *RecentLinesGetter_Execute_Call) Return(_a0 entity.LineMap, _a1 error) *RecentLinesGetter_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RecentLinesGetter_Execute_Call) RunAndReturn(run func(context.Context, []string) (entity.LineMap, error)) *RecentLinesGetter_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewRecentLinesGetter creates a new instance of RecentLinesGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRecentLinesGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *RecentLinesGetter {
	mock := &RecentLinesGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
