// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/supressionstop/xenking_test_1/internal/usecase/entity"
)

// SaveLineToStorage is an autogenerated mock type for the SaveLineToStorage type
type SaveLineToStorage struct {
	mock.Mock
}

type SaveLineToStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *SaveLineToStorage) EXPECT() *SaveLineToStorage_Expecter {
	return &SaveLineToStorage_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, line
func (_m *SaveLineToStorage) Execute(ctx context.Context, line entity.Line) (entity.Line, error) {
	ret := _m.Called(ctx, line)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 entity.Line
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Line) (entity.Line, error)); ok {
		return rf(ctx, line)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Line) entity.Line); ok {
		r0 = rf(ctx, line)
	} else {
		r0 = ret.Get(0).(entity.Line)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Line) error); ok {
		r1 = rf(ctx, line)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveLineToStorage_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type SaveLineToStorage_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - line entity.Line
func (_e *SaveLineToStorage_Expecter) Execute(ctx interface{}, line interface{}) *SaveLineToStorage_Execute_Call {
	return &SaveLineToStorage_Execute_Call{Call: _e.mock.On("Execute", ctx, line)}
}

func (_c *SaveLineToStorage_Execute_Call) Run(run func(ctx context.Context, line entity.Line)) *SaveLineToStorage_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Line))
	})
	return _c
}

func (_c *SaveLineToStorage_Execute_Call) Return(_a0 entity.Line, _a1 error) *SaveLineToStorage_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SaveLineToStorage_Execute_Call) RunAndReturn(run func(context.Context, entity.Line) (entity.Line, error)) *SaveLineToStorage_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewSaveLineToStorage creates a new instance of SaveLineToStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSaveLineToStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *SaveLineToStorage {
	mock := &SaveLineToStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
