services:
  processor:
    build:
      context: ./
      dockerfile: docker/processor/Dockerfile.debug
    ports:
      - "40000:40000"
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE