// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const saveLine = `-- name: SaveLine :one
INSERT INTO lines (
    sport, rate, created_at
) VALUES (
             $1, $2, $3
         )
RETURNING id, sport, rate, created_at
`

type SaveLineParams struct {
	Sport     string
	Rate      pgtype.Numeric
	CreatedAt pgtype.Timestamp
}

func (q *Queries) SaveLine(ctx context.Context, arg SaveLineParams) (Line, error) {
	row := q.db.QueryRow(ctx, saveLine, arg.Sport, arg.Rate, arg.CreatedAt)
	var i Line
	err := row.Scan(
		&i.ID,
		&i.Sport,
		&i.Rate,
		&i.CreatedAt,
	)
	return i, err
}
