FROM golang:1.23.1-alpine3.20 AS builder
RUN go install github.com/go-delve/delve/cmd/dlv@latest
WORKDIR /app
COPY go.mod go.mod
RUN go mod download
COPY . .
RUN go build -v -gcflags="all=-N -l" -o ./processor ./cmd/processor

FROM alpine
WORKDIR /app
COPY config config
COPY --from=builder /app/processor ./processor
COPY --from=builder /go/bin/dlv ./dlv
CMD ["./dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "./processor"]