version: "2"
sql:
  - engine: "postgresql"
    queries: "../internal/storage/queries.sql"
    schema: "../internal/storage/migrations"
    gen:
      go:
        package: "storage"
        out: "../internal/storage"
        sql_package: "pgx/v5"