// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: lines.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Subscribe struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sports   []string `protobuf:"bytes,1,rep,name=sports,proto3" json:"sports,omitempty"`
	Interval int32    `protobuf:"varint,2,opt,name=interval,proto3" json:"interval,omitempty"`
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lines_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_lines_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_lines_proto_rawDescGZIP(), []int{0}
}

func (x *Subscribe) GetSports() []string {
	if x != nil {
		return x.Sports
	}
	return nil
}

func (x *Subscribe) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

type LinesData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *LinesData) Reset() {
	*x = LinesData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lines_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinesData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinesData) ProtoMessage() {}

func (x *LinesData) ProtoReflect() protoreflect.Message {
	mi := &file_lines_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinesData.ProtoReflect.Descriptor instead.
func (*LinesData) Descriptor() ([]byte, []int) {
	return file_lines_proto_rawDescGZIP(), []int{1}
}

func (x *LinesData) GetResults() []*Result {
	if x != nil {
		return x.Results
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sport string `protobuf:"bytes,1,opt,name=sport,proto3" json:"sport,omitempty"`
	Rate  string `protobuf:"bytes,2,opt,name=rate,proto3" json:"rate,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lines_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_lines_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_lines_proto_rawDescGZIP(), []int{2}
}

func (x *Result) GetSport() string {
	if x != nil {
		return x.Sport
	}
	return ""
}

func (x *Result) GetRate() string {
	if x != nil {
		return x.Rate
	}
	return ""
}

var File_lines_proto protoreflect.FileDescriptor

var file_lines_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6c,
	0x69, 0x6e, 0x65, 0x73, 0x22, 0x3f, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x76, 0x61, 0x6c, 0x22, 0x34, 0x0a, 0x09, 0x4c, 0x69, 0x6e, 0x65, 0x73, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x27, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x32, 0x0a, 0x06, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x32,
	0x4b, 0x0a, 0x05, 0x4c, 0x69, 0x6e, 0x65, 0x73, 0x12, 0x42, 0x0a, 0x16, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x4f, 0x6e, 0x53, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x4c, 0x69, 0x6e,
	0x65, 0x73, 0x12, 0x10, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x1a, 0x10, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x4c, 0x69, 0x6e,
	0x65, 0x73, 0x44, 0x61, 0x74, 0x61, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x23, 0x5a, 0x21,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lines_proto_rawDescOnce sync.Once
	file_lines_proto_rawDescData = file_lines_proto_rawDesc
)

func file_lines_proto_rawDescGZIP() []byte {
	file_lines_proto_rawDescOnce.Do(func() {
		file_lines_proto_rawDescData = protoimpl.X.CompressGZIP(file_lines_proto_rawDescData)
	})
	return file_lines_proto_rawDescData
}

var file_lines_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_lines_proto_goTypes = []any{
	(*Subscribe)(nil), // 0: lines.Subscribe
	(*LinesData)(nil), // 1: lines.LinesData
	(*Result)(nil),    // 2: lines.Result
}
var file_lines_proto_depIdxs = []int32{
	2, // 0: lines.LinesData.results:type_name -> lines.Result
	0, // 1: lines.Lines.SubscribeOnSportsLines:input_type -> lines.Subscribe
	1, // 2: lines.Lines.SubscribeOnSportsLines:output_type -> lines.LinesData
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_lines_proto_init() }
func file_lines_proto_init() {
	if File_lines_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lines_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Subscribe); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lines_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*LinesData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lines_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lines_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lines_proto_goTypes,
		DependencyIndexes: file_lines_proto_depIdxs,
		MessageInfos:      file_lines_proto_msgTypes,
	}.Build()
	File_lines_proto = out.File
	file_lines_proto_rawDesc = nil
	file_lines_proto_goTypes = nil
	file_lines_proto_depIdxs = nil
}
