openapi: 3.0.0
info:
  version: 0.1.0
  title: Xenking №1 REST API
  description: REST API for lines sync service.

servers:
  - url: https://localhost:48001

paths:
  /ready:
    get:
      description: Check if first lines sync is done.
      responses:
        '200':
          description: App storage is online and all lines are synced.
        '403':
          description: App storage is offline or lines is not synced yet

